name: deploy_to_firebase_hosting

on: 
  push:
    branches:
      - master


jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install deps
        run: yarn

      - name: Build docs
        run: yarn docs:build

      - name: Deploy to Firebase
        uses: matter-labs/firebase-action@master
        with:
          args: deploy --project zksync-js-docs --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
